### ISSUE TITLE
Incorrect Versioning for WAILA (HWYLA) to Work

### ISSUE THREAD

**Issue by Coraline77447** [AHilyard/AdvancementPlaques#1]
I'm having issues with AdvancementPlaques and WAILA aka HWYLA.
The current version of WAILA for 1.16.5 as of it's full release is 8.0.1 while it's beta version is 8.0.6 and neither one of them is working with the latest version of AdvancementPlaques and now requires 2.7.1 or
 higher when 8.0.1 is higher than 2.7.1

![Screenshot (5)](https://user-images.githubusercontent.com/72243304/126493922-e46bcbb6-ae2e-471a-b21b-81010afc2206.png)

![Screenshot (6)](https://user-images.githubusercontent.com/72243304/126494216-e8b24f94-3923-40cd-b18d-2870d236ef3d.png)

Look at what's highlighted in the second screenshot which is it's beta version btw.

Here's the crash log: https://pastebin.com/L05nJTBR

For the time being I'm going to revert back to the last version of this mod that was working with WAILA (HWYLA) while I wait for this to get resolved.

One last thing, I've tried to dig deeper into WAILA to find it's true version and idk where it may be within it's files without messing up WAILA itself since I don't know if 8.0.1 or 8.0.6 are it's true versioning numbers and why I say this is cause as you can see in the first screenshot that MC is telling me that WAILA's 1.16.5 version is 1.10.11-B79_1.16.2.
Also WAILA hasn't been updated in months as of a full release version (Feb 1st)...

WAIT A SEC!
Does WAILA (HWYLA) use the same versioning as Bookshelf???
If so then why is MC telling me that I need the latest version of WAILA instead of Bookshelf for the latest version of AdvancementPlaques?!?
Let me see if updating bookshelf fixes this mess and if it does then I'll close this as soon as I'm passed mod loading....

**Comment by AHilyard** [comment]
Ah, interesting, I think I know what is happening here.  This is an unfortunate case of multiple mods using the same mod ID but having different versioning.  Waila, Hwyla, and Jade all use the mod ID "waila", but the version requirement in the latest Advancement Plaques update is based on the versioning of Jade (it is the most recently-updated fork of Waila).
In order to fix this, I will remove the version requirements altogether.

**Comment by AHilyard** [comment]
This has been fixed in https://github.com/AHilyard/AdvancementPlaques/commit/fa2b8b2a3a99feddb4d0da9cbe2a665b5b62fd93.  Look for Advancement Plaques 1.2.4 on CurseForge once it's available.  Enjoy!

**Comment by Coraline77447** [comment]
Thanks for fixing the issue, But I'd thought that the versioning thing as of Waila was based off from Bookshelf library mod which is owned by the same owner of Waila (Hwyla, Jade) i think cause in the screenshot above looks like bookshelf's versioning.
Also I don't use Jade cause as said that it's another fork for Waila like Hwyla is. 
Even tho I've downloaded Waila in it's curseforge page but when loaded mc says Hwyla instead of Waila.
I don't download Hwyla itself at all anymore cause Waila nowadays is Hwyla, like as if it morphed/transformed itself into Hwyla entirely.
