### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by riverablue** [AHilyard/AdvancementPlaques#10]
Hello~! for whatever reason both Achievement plaques & plates crash the game on startup with **no crash report**
It simply closes the game & doesn't take me back to the launcher. 

Current mods running on **1.18.1 FABRIC** are:
1. Terralith 
2. levelz 
4. inven hud 
5. mo structures 
6. backslot + addon 
7. comforts 
8. Villnames 
9.wandering collect 
10. rpgz 
11. when dungeons arise
12. loot beams 
13. advanced compass 
14. end remastered 
15. bountiful 
Thankyou~!

**Comment by AHilyard** [comment]
@riverablue Please make sure you have the latest version of Iceberg installed as well, which is required for Advancement Plaques to work.  If you still have issues, please ensure you've installed the Fabric version of Advancement Plaques and are using the latest version of the Fabric API.  Feel free to reopen this issue if you're still experiencing problems after this.
