### ISSUE TITLE
[BUG] Hide WTHIT, WYL, WAYLA etc does not work

### ISSUE THREAD

**Issue by ardissaps** [AHilyard/AdvancementPlaques#12]
They are not hidden at all still displayed under plaque when appear

**Comment by AHilyard** [comment]
What version of Minecraft are you using and Forge or Fabric?

**Comment by ardissaps** [comment]
> What version of Minecraft are you using and Forge or Fabric?

1.18.2 with Fabric

**Comment by AHilyard** [comment]
This has been fixed in version 1.4.5, enjoy. 😄
