### ISSUE TITLE
It Spam Console When Advancement Trigger

### ISSUE THREAD

**Issue by ardissaps** [AHilyard/AdvancementPlaques#14]
Clink The Link on the picture for detail and scroll to very bottom :
[![image](https://user-images.githubusercontent.com/82106625/175807237-72b4d727-a30d-439e-a571-7e45d2e2bda1.png)](https://paste.atlauncher.com/view/daf9bfa6-8a10-43c4-bac4-b7db20d12994)

**Comment by AHilyard** [comment]
If possible, could you downgrade WTHIT to 4.4.1 and test again?  I suspect there was a breaking change in the version after that.

**Comment by ardissaps** [comment]
> downgrade WTHIT to 4.4.1

Look like that version is not available for 1.18.2 :
![image](https://user-images.githubusercontent.com/82106625/175858235-6203f715-8dd3-4268-acdb-5aa1f4512e09.png)

**Comment by AHilyard** [comment]
Ah, that's unfortunate.  I will look into fixing this, I just need to reproduce it locally first to verify my suspicion.

**Comment by AHilyard** [comment]
This has been fixed in version 1.4.5, enjoy. 😄
