### ISSUE TITLE
Fabric 1.19.1

### ISSUE THREAD

**Issue by Wizkid305** [AHilyard/AdvancementPlaques#16]
Are there any plans to update fabric to 1.19.1 and do you have a release window your expecting. Take your time I'm just asking.

**Comment by AHilyard** [comment]
Thank you for the reminder, I believe most of my mods already support 1.19.1 without changing any code.  I'll verify later today for Advancement Plaques.

**Comment by AHilyard** [comment]
I've verified that the 1.19 version also works on 1.19.1 and updated the CurseForge listing accordingly.
