### ISSUE TITLE
Crashes on Forge along with Player Animator

### ISSUE THREAD

**Issue by AverageDood** [AHilyard/AdvancementPlaques#17]
Before anything: I have tried running both Iceberg and Player Animator together, and the game runs just fine, so this error has been checked to occur only when Advancement Plaques comes in.

Advancement Plaques seems to have some kind of mixin conflict with Player Animator (https://www.curseforge.com/minecraft/mc-mods/playeranimator which is a dependency for mods like Better Combat or Combat Roll) that prevents the game from running.

Minecraft version: 1.19.2
Modloader: Forge
Advancement Plaques version: 1.4.4.1

I have tried checking for Advancement Plaques updates, but said update, 1.4.5.1, seems to be available only for Minecraft 1.18, not 1.19

Here's the log thrown at me by the launcher: https://mclo.gs/XiuYyGB

**Comment by AHilyard** [comment]
Can you please upload your latest.log file as well?  It will be very helpful for troubleshooting.

**Comment by AverageDood** [comment]
Actually I think I should report it to both Iceberg and Player Animations. Turns out after one more test, not only Advancement Plaques triggers the error, but also the mods that I mentioned depend on Player Animation, Better Combat and Combat Roll.

Player Animation and Iceberg can co-exist by themselves, is enabling the mods that depend on them what triggers the issue.

Sorry for the inconvenience
