### ISSUE TITLE
[Feature Request] Config options for time

### ISSUE THREAD

**Issue by AngleWyrm10** [AHilyard/AdvancementPlaques#2]
I love the plaques, but due to frame rate and mod load they can take longer than I would prefer to fade in.

**Comment by AHilyard** [comment]
Sure thing, I've added this feature in https://github.com/AHilyard/AdvancementPlaques/commit/0ec4ce0e383f8a9dc5151407495b8247fb7f88a3.  Look for version 1.2.4 on CurseForge once it's available.  Enjoy!
