### ISSUE TITLE
Forge 1.18 Crashing with only minimal mods installed

### ISSUE THREAD

**Issue by mysticetus09** [AHilyard/AdvancementPlaques#22]
[crash-2023-01-09_20.44.33-fml.txt](https://github.com/AHilyard/AdvancementPlaques/files/10373273/crash-2023-01-09_20.44.33-fml.txt)

**Comment by mysticetus09** [comment]
Both Advancement Plaques and Legendary Tooltips was making my game crash. I wanted to use these two mods that's why I issued a report.

**Comment by AHilyard** [comment]
This crash report indicates that you are trying to use a mod called "Traveler's Titles" without installing the dependency "Yung's API".  Neither Legendary Tooltips nor Advancement Plaques are mentioned in this crash.
