### ISSUE TITLE
False file uploaded on Modrinth

### ISSUE THREAD

**Issue by latipun7** [AHilyard/AdvancementPlaques#24]
![image](https://user-images.githubusercontent.com/20012970/224557449-e35e9bd3-f618-43f5-8e2f-004fa577288b.png)

I downloaded those three mods under `fabric` loader from Modrinth, but error upon launching with missing `forgeconfigapiport`. Of course, I'm on fabric, so that three mods would missing forge API.

**Comment by AHilyard** [comment]
I think you've misunderstood, Forge Config API Port is a Fabric mod that ports Forge's configuration system.  You can find it here: https://modrinth.com/mod/forge-config-api-port

**Comment by latipun7** [comment]
Ohh yeah, thank you. Sorry for my misunderstanding. Might as well add that as required dependencies, then. Thank you 🙏

**Comment by AHilyard** [comment]
No worries!  Thanks for the reminder, I've added it as a required dependency to those mods.
