### ISSUE TITLE
[Forge-1.18.2] Incompatible with Advancement Screenshot

### ISSUE THREAD

**Issue by qznfbnj** [AHilyard/AdvancementPlaques#25]
With the AdvancementPlaques mod installed, the Advancement Screenshot mod cannot take screenshot one second after an advancement be completed.
Forge-1.18.2-40.2.1
advancementscreenshot_1.18.2-4.1 (with collective-1.18.2-6.53)
AdvancementPlaques-1.18.2-1.4.5.1 (with Iceberg-1.18.2-forge-1.0.49)
https://github.com/ricksouth/serilum-mc-mods/issues/1773

**Comment by ricksouth** [comment]
Hi, author of Advancement Screenshot here. It seems like you are overriding the entire toast class. Would it be possible to use a mixin instead? I can't add compatibilty in this case.

**Comment by ricksouth** [comment]
Looks like this was fixed on the latest release of Advancement Plaques: https://github.com/Serilum/.issue-tracker/issues/2312. Thanks!
