### ISSUE TITLE
1.20

### ISSUE THREAD

**Issue by Monke132** [AHilyard/AdvancementPlaques#27]
will 1.20 Support be Arriving Soon?

**Comment by BenTheMan69** [comment]
I hope there will because this mod is freaking awesome!

**Comment by OBS3SS1ON** [comment]
1.20.1? I need this ;(

**Comment by SeanJohnGamings** [comment]
Desperately need 1.20 for the modpack im working on... it's weird they skipped to 1.20.1?

**Comment by AHilyard** [comment]
Hey guys, Advancement Plaques is available for both 1.20 and 1.20.1 now.

https://legacy.curseforge.com/minecraft/mc-mods/advancement-plaques/files/all
https://legacy.curseforge.com/minecraft/mc-mods/advancement-plaques-fabric/files/all

Enjoy! 😄
