### ISSUE TITLE
[1.20.1] When an advancement plaque is fading out, tooltips in inventory also gets faded out.

### ISSUE THREAD

**Issue by Gbergz** [AHilyard/AdvancementPlaques#32]
When an advancement plaque is fading out, tooltips in inventory also gets faded out.

### **Video:**
https://streamable.com/5xk7ci

### Versions:
MC: 1.20.1
Forge: 47.1.3
Advancement Plaques: 1.4.10
Iceberg: 1.1.13

**Comment by AlisonHuang777** [comment]
Same here. Playing Prominence II modpack.

**Comment by Lush-Pages** [comment]
I've experienced it as well. Tested Fabric versions 1.4.9, 1.4.10, and 1.4.11 and it occurs in all three. With Legendary Tooltips installed, items with 3D previews, like armor and weapons, seem to be unaffected.

**Comment by Diedntgo** [comment]
Also experiencing this issue in 1.20.1-forge-1.5.1
Tooltips fade for me while advancements fade as well

**Comment by rumrunner0** [comment]
SAME for 1.20.1 fabric (mod version 1.4.11)
It's Jan 30, 2024 now, just in case.

Is there ANY chance to fix this bug for 1.20.1?


please?

**Comment by Denixerianer** [comment]
same problem very annoying

**Comment by xlea99** [comment]
Same problem, 1.20.1 Forge (mod version 1.5.1). If an Advancement plaque is fading, all Legendary Tooltips fade too. Issue seems to be that both mods use the same "fade" logic so one AP fades, so does Legendary Tooltips

**Comment by Lucipo** [comment]
Issue persists w/ Legendary Tooltips mod in forge 1.5.1, even though the issue was declared as fixed in v1.5.0

**Comment by Fyoncle** [comment]
Same problem, 1.20.1 Fabric, when the fix? :(

**Comment by AHilyard** [comment]
I have just released all of the latest changes backported to 1.20.1 which includes a fix for this issue.  Enjoy everyone. 😄
