### ISSUE TITLE
[Duplicate Issue] Fading Out Tooltips

### ISSUE THREAD

**Issue by Fyoncle** [AHilyard/AdvancementPlaques#39]
This issue is a duplicate of https://github.com/AHilyard/AdvancementPlaques/issues/32 since the old post is seems to be never responded by the dev, i opened this duplicate one to make the old issue visible.

Basically the bug is all about when getting an advancement go to the tooltip of the green text in the chat, and see it fading out when advancement is also fading out.

**Comment by brisingraerowing** [comment]
This affects ALL tooltips, FWIW. Even in inventories. Is annoying.

**Comment by Fyoncle** [comment]
> This affects ALL tooltips, FWIW. Even in inventories. Is annoying.

Yeah its annoying but dev seems like doesn't care about 1.20.1 anymore

**Comment by AHilyard** [comment]
I have just released all of the latest changes backported to 1.20.1 which includes a fix for this issue.  Enjoy everyone. 😄
