### ISSUE TITLE
NeoForge Config issues from update 21.0.143

### ISSUE THREAD

**Issue by Zelioth** [AHilyard/AdvancementPlaques#44]
![image](https://github.com/user-attachments/assets/da7239b9-98b0-41bd-bbde-a7cc0b540069)

NeoForge has changes something for configs and a lot of mods are affected and not loading in the latest releases. 

So far all of your mods give this same error when loaded on NeoForge 21.0.143 for 1.21.

[latest.log](https://github.com/user-attachments/files/16419201/latest.log)

**Comment by AHilyard** [comment]
Thank you for bringing this up, it has been resolved in the latest Iceberg release.
