### ISSUE TITLE
Tooltips/Block UI fading into black with the animation fading. 

### ISSUE THREAD

**Issue by TheShadyyOneYT** [AHilyard/AdvancementPlaques#45]
Mentioned in #39 and #32 but I will go in more into detail.

First off, this is the issue: https://youtu.be/x8bDHUGE8I4

Secondly, here is how to re-create it:
1. Download Advancement Plaques
2. Launch the game
3. execute the command: `/advancement grant [Username] only Minecraft:story/upgrade_tools`
4. hover over any item at all. 
5. wait till the fading animation plays and the tooltips starts to fade into black matching the fading animation of the plaque

Versions:
Fabric Modloader: 0.16.2 (any recent ones work)
Fabric API: 0.92.2
Advancement Plaques: 1.4.11
Game Version: 1.20.1

This would be lovely if you can fix this.

### Logs:
`latest.log`
https://pastebin.com/tTfsd2gr

**Comment by Fyoncle** [comment]
Pain that we have to open 3 issues just to get this fixed, i wonder why dev doesn't mind this :(

**Comment by TheShadyyOneYT** [comment]
> Pain that we have to open 3 issues just to get this fixed, i wonder why dev doesn't mind this :(

No kidding, I’m a little disappointed, not even a response saying: “we’re busy, we will work on it as soon as I/we can” or a confirmation that they saw it

**Comment by Fyoncle** [comment]
> 

Yeah! Exactly that, why not just say that you're busy or something but give a **feeling** that you guys never check your own mod's github reports..

**Comment by TheShadyyOneYT** [comment]
> > 
> 
> Yeah! Exactly that, why not just say that you're busy or something but give a **feeling** that you guys never check your own mod's github reports..

Yeah, and usually duplicates get closed and merged into one report. Haven’t even done that yet

**Comment by Fyoncle** [comment]
> > > 
> > 
> > 
> > Yeah! Exactly that, why not just say that you're busy or something but give a **feeling** that you guys never check your own mod's github reports..
> 
> Yeah, and usually duplicates get closed and merged into one report. Haven’t even done that yet

Yep... disappointing :(

**Comment by Fyoncle** [comment]
![image](https://github.com/user-attachments/assets/5241e198-9cbf-401f-80bd-efa541e7939a)
Fyoncle saved the day. @TheShadyyOneYT

**Comment by TheShadyyOneYT** [comment]
> ![image](https://private-user-images.githubusercontent.com/63975256/368022010-5241e198-9cbf-401f-80bd-efa541e7939a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NTU3NDUsIm5iZiI6MTcyNjU1NTQ0NSwicGF0aCI6Ii82Mzk3NTI1Ni8zNjgwMjIwMTAtNTI0MWUxOTgtOWNiZi00MDFmLTgwYmQtZWZhNTQxZTc5MzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA2NDQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3NTUwOTZhNzYxMDRmN2Y5MDczNGZmM2U4OTUzM2RhYjQ2NTViOTkwNzNhZmE1ZDk5YzYwM2MxNmIzOGVjMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vlEpQyixE3sd4oVEU1bWxM1ZPaEG476NLn-njG1KkI0) Fyoncle saved the day. @TheShadyyOneYT

W, thanks

**Comment by Fyoncle** [comment]
> > ![image](https://private-user-images.githubusercontent.com/63975256/368022010-5241e198-9cbf-401f-80bd-efa541e7939a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NTU3NDUsIm5iZiI6MTcyNjU1NTQ0NSwicGF0aCI6Ii82Mzk3NTI1Ni8zNjgwMjIwMTAtNTI0MWUxOTgtOWNiZi00MDFmLTgwYmQtZWZhNTQxZTc5MzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA2NDQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3NTUwOTZhNzYxMDRmN2Y5MDczNGZmM2U4OTUzM2RhYjQ2NTViOTkwNzNhZmE1ZDk5YzYwM2MxNmIzOGVjMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vlEpQyixE3sd4oVEU1bWxM1ZPaEG476NLn-njG1KkI0) Fyoncle saved the day. @TheShadyyOneYT
> 
> W, thanks

❤️

**Comment by Fyoncle** [comment]
Backport coming soon.

**Comment by TheShadyyOneYT** [comment]
> Backport coming soon.

Heck yeah

**Comment by Fyoncle** [comment]
Fix is today.

**Comment by AHilyard** [comment]
I have just released all of the latest changes backported to 1.20.1 which includes a fix for this issue.  Enjoy everyone. 😄 
(Thank you for bringing this to my attention @Fyoncle)
