### ISSUE TITLE
1.20.1 Fabric Advancement Screenshot Incompatibility

### ISSUE THREAD

**Issue by Shodelat** [AHilyard/AdvancementPlaques#46]
Last mod version for 1.20.1 fabric was released a long time ago, Advancement Screenshot doesn't work with it😭

**Comment by AHilyard** [comment]
I've just backported the latest changes including support for Advancement Screenshot on 1.20.1 Fabric. :)

**Comment by Shodelat** [comment]
> I've just backported the latest changes including support for Advancement Screenshot on 1.20.1 Fabric. :)

god blesses you
