### ISSUE TITLE
Dependency not clear

### ISSUE THREAD

**Issue by sororbadr** [AHilyard/AdvancementPlaques#6]
advancement plaques' Iceberg dependency isn't mentioned when the game crashes due to it not being in the mods folder, instead, the game just crashes without giving a crash report.

**Comment by AHilyard** [comment]
Hmm, that is not normal behavior, I don't think I've seen that before.  I need more information:
**Minecraft version
Forge or Fabric
Mod version**

**Comment by AHilyard** [comment]
I think this was referencing the Fabric 1.18 version of the mod, and this issue has been fixed in the latest release so I am closing this issue.  If it was for a different version please create a new issue with that information included.
